# Generated by Django 4.0.4 on 2023-10-12 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAreaAffected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('areaAffected', models.CharField(max_length=100, verbose_name='Área afectada')),
            ],
            options={
                'verbose_name_plural': 'Área del negocio afectada',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Unidad de Negocio',
            },
        ),
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=40, verbose_name='Nombre del caso de prueba')),
                ('caseTestDescription', models.TextField(verbose_name='Descripción')),
                ('caseTestPreconditions', models.TextField(verbose_name='Precondiciones')),
                ('caseOrder', models.PositiveIntegerField(verbose_name='Orden del caso de prueba')),
                ('caseSteps', models.TextField(verbose_name='Pasos a seguir')),
                ('caseExpectedOutcome', models.TextField(verbose_name='Resultado Esperado')),
            ],
            options={
                'verbose_name_plural': 'Caso de Prueba',
            },
        ),
        migrations.CreateModel(
            name='ImplementationRelease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ImplementationDate', models.DateField(verbose_name='Fecha de Implementación')),
                ('developerInCharge', models.TextField(verbose_name='Desarrollador a cargo')),
                ('qaInCharge', models.TextField(verbose_name='Tester a cargo')),
                ('descriptionResults', models.TextField(verbose_name='Descripción de resultados')),
                ('testEvidence', models.CharField(max_length=50, verbose_name='Evidencias de las pruebas')),
            ],
            options={
                'verbose_name_plural': 'Implementación de la Entrega',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre Plataforma')),
                ('link', models.CharField(max_length=300, verbose_name='Link de la plataforma')),
            ],
            options={
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('startDate', models.DateField(auto_created=True, verbose_name='Fecha de Inicio')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nombre Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('BAJ', 'BAJA'), ('MED', 'MEDIA'), ('ALT', 'ALTA')], max_length=10, verbose_name='Prioridad')),
                ('version', models.IntegerField(verbose_name='Versión')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignedTo_user_p', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.businessunit', verbose_name='Unidad de negocio')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_user_p', to=settings.AUTH_USER_MODEL, verbose_name='Desarrollador')),
                ('productOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productOwner_user_p', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del producto')),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_user_p', to=settings.AUTH_USER_MODEL, verbose_name='Tester de Calidad')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter_user_p', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('stakeHolder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeh_user_p', to=settings.AUTH_USER_MODEL, verbose_name='StakeHolder')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='QaDocumentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('TestPlans', models.TextField(verbose_name='Nombre del Plan de Pruebas')),
                ('productOwnerApproval', models.BooleanField(default=False, verbose_name='Aprobación del Dueño del producto')),
                ('developerApproval', models.BooleanField(default=False, verbose_name='Aprobación del Desarrollador')),
                ('importanceOfTestCases', models.CharField(choices=[('BAJA', 'Baja'), ('MED', 'Media'), ('ALTA', 'Alta')], max_length=10, verbose_name='Importancia de los casos de PRueba')),
                ('evidenceOfTheTestPlans', models.TextField(verbose_name='Evidencias del plan de pruebas')),
            ],
            options={
                'verbose_name_plural': 'Documentaciones QA',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de Entrega')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('BAJ', 'BAJA'), ('MED', 'MEDIA'), ('ALT', 'ALTA')], max_length=10, verbose_name='Prioridad')),
                ('version', models.IntegerField(verbose_name='Versión')),
                ('qaDeploymentPlanningDate', models.DateField(blank=True, verbose_name='Fecha planificada despliegue QA')),
                ('testPlanCreationDate', models.DateField(blank=True, verbose_name='Fecha de creación del plan de pruebas')),
                ('testStartDate', models.DateField(blank=True, verbose_name='Fecha de inicio de pruebas')),
                ('testEndDate', models.DateField(blank=True, verbose_name='Fecha de finalización de pruebas')),
                ('plannedImplementationDate', models.DateField(blank=True, verbose_name='Fecha planificada de Implementación')),
                ('finalImplementationDate', models.DateField(blank=True, verbose_name='Fecha de implementación')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignedTo', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_user', to=settings.AUTH_USER_MODEL, verbose_name='Desarrollador')),
                ('productOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productOwner_user', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del producto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project', verbose_name='Proyecto')),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_user', to=settings.AUTH_USER_MODEL, verbose_name='Tester')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Descripción')),
                ('target_flow', models.CharField(max_length=50, verbose_name='Objetivo Flujo')),
                ('status', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTests',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipo de pruebas',
            },
        ),
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre tipo tarea')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Tarea',
            },
        ),
        migrations.CreateModel(
            name='TestEjecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('generalDescription', models.TextField(verbose_name='Descripción general')),
                ('implementationRelease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.implementationrelease', verbose_name='Entrega relacionada')),
            ],
            options={
                'verbose_name_plural': 'Ejecución de Pruebas',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre Tarea')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('associatedRealease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release', verbose_name='Entrega relacionada')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Estado')),
                ('typeTask', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typetask', verbose_name='Tipo de Tarea')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.CharField(max_length=20, verbose_name='Descripción')),
                ('record_id', models.IntegerField(verbose_name='Identificador de Descripción')),
                ('transDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Historial de Estados',
            },
        ),
        migrations.CreateModel(
            name='ReportedBugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.CharField(max_length=100, verbose_name='Título del error')),
                ('typeInput', models.CharField(max_length=300, verbose_name='Descripción del Error')),
                ('status', models.CharField(choices=[('New', 'Nuevo'), ('MoreData', 'Es necesaria más información'), ('Assig', 'Asignado'), ('Resolv', 'Resuelto'), ('Close', 'Cerrado')], max_length=10, verbose_name='Estado del Reporte')),
                ('category', models.CharField(choices=[('NoDisp', 'Funcionalidad no disponible'), ('Handling', 'Manejo de errores definidos'), ('IncImp', 'Implementación incorrecta'), ('improve', 'Mejora'), ('Secure', 'Error de Seguridad'), ('UserInt', 'Interfaz de usuario'), ('Usab', 'Usabilidad'), ('Navi', 'Navigabilidad')], max_length=10, verbose_name='Categoría')),
                ('priority', models.CharField(choices=[('Block', 'Bloqueado'), ('Urg', 'Urgente'), ('High', 'Alto'), ('Ave', 'Medio'), ('Low', 'Bajo')], max_length=10, verbose_name='Prioridad')),
                ('severity', models.CharField(choices=[('Cri', 'Crítico'), ('Ma', 'Mayor'), ('Mi', 'Menor'), ('Sug', 'Sugerencia')], max_length=10, verbose_name='Severidad')),
                ('frenquency', models.CharField(choices=[('Alw', 'Siempre'), ('Som', 'A veces'), ('Rand', 'Aleatorio'), ('NotTri', 'No se ha intentado'), ('NotRep', 'No reproducible'), ('Unknown', 'Desconocido')], max_length=10, verbose_name='Frecuencia')),
                ('summary', models.CharField(max_length=50, verbose_name='Resumen del error')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('stepsToReproduce', models.TextField(verbose_name='Pasos para replicar')),
                ('assignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bug_assignedto_user', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporter_bug_user', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name_plural': 'Reporte de Errores',
            },
        ),
        migrations.CreateModel(
            name='ReleasePlatformAffected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.platform', verbose_name='Plataforma Afectada')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release', verbose_name='Entrega relacionada')),
            ],
            options={
                'verbose_name_plural': 'Plataforma afectada por la Entrega',
            },
        ),
        migrations.CreateModel(
            name='ReleaseCommercialApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('businessAreaAffected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.businessareaaffected', verbose_name='Área del negocio afectada')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release', verbose_name='Entrega relacionada')),
            ],
            options={
                'verbose_name_plural': 'Aprobación comercial de la entrega',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='release',
            name='typeOfTests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests', verbose_name='Tipo de Prueba'),
        ),
        migrations.CreateModel(
            name='QaDocumentationCaseTestImp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('importanceOfTestCases', models.CharField(choices=[('BAJA', 'Baja'), ('MED', 'Media'), ('ALTA', 'Alta')], max_length=10, verbose_name='Importancia de los casos de prueba')),
                ('caseTest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.casetest', verbose_name='Caso de prueba')),
                ('qaDocumentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qadocumentation', verbose_name='Documentación QA')),
            ],
            options={
                'verbose_name_plural': 'Importancia de los casos de prueba en las Documentaciones QA',
            },
        ),
        migrations.AddField(
            model_name='qadocumentation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeOfTests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests', verbose_name='Tipo de Prueba'),
        ),
        migrations.AddField(
            model_name='implementationrelease',
            name='Documentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qadocumentation', verbose_name='Documentación'),
        ),
        migrations.AddField(
            model_name='implementationrelease',
            name='idRelease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release', verbose_name='Entrega relacionada'),
        ),
        migrations.CreateModel(
            name='ChecklistDocumentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('qaDocumentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qadocumentation', verbose_name='Documentación QA')),
                ('releasePlatformAffected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.releaseplatformaffected', verbose_name='Entrega relacionada')),
                ('typeOfTests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests', verbose_name='Tipos de prueba')),
            ],
            options={
                'verbose_name_plural': 'Lista de Verificación de Documentaciones',
            },
        ),
        migrations.AddField(
            model_name='casetest',
            name='testEjecution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.testejecution', verbose_name='Plan de pruebas relacionado'),
        ),
    ]
