# Generated by Django 4.2.1 on 2023-07-27 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAreaAffected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('areaAffected', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationRelease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('ImplementationDate', models.DateField()),
                ('developerInCharge', models.TextField()),
                ('qaInCharge', models.TextField()),
                ('descriptionResults', models.TextField()),
                ('testEvidence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('startDate', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('BAJ', 'BAJA'), ('MED', 'MEDIA'), ('ALT', 'ALTA')], max_length=10)),
                ('version', models.IntegerField()),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignedTo_user_p', to=settings.AUTH_USER_MODEL)),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.businessunit')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_user_p', to=settings.AUTH_USER_MODEL)),
                ('productOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productOwner_user_p', to=settings.AUTH_USER_MODEL)),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_user_p', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter_user_p', to=settings.AUTH_USER_MODEL)),
                ('stakeHolder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeh_user_p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('BAJ', 'BAJA'), ('MED', 'MEDIA'), ('ALT', 'ALTA')], max_length=10)),
                ('version', models.IntegerField()),
                ('qaDeploymentPlanningDate', models.DateField()),
                ('testPlanCreationDate', models.DateField()),
                ('testStartDate', models.DateField()),
                ('testEndDate', models.DateField()),
                ('plannedImplementationDate', models.DateField()),
                ('finalImplementationDate', models.DateField()),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignedTo', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_user', to=settings.AUTH_USER_MODEL)),
                ('productOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productOwner_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_user', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedBugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('typeInput', models.CharField(max_length=100)),
                ('reportedBy', models.CharField(max_length=100)),
                ('assignedTo', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('MoreData', 'More data is needed'), ('Assig', 'Assigned'), ('Resolv', 'Resolved'), ('Close', 'Close')], max_length=10)),
                ('category', models.CharField(choices=[('NoDisp', 'Functionality Not Available'), ('Handling', 'Error Handling'), ('IncImp', 'Incorrect Implementation'), ('improve', 'Improvement'), ('Secure', 'Security'), ('UserInt', 'User Interface'), ('Usab', 'Usability'), ('Navi', 'Navigability')], max_length=10)),
                ('priority', models.CharField(choices=[('Block', 'Blocking'), ('Urg', 'Urgent'), ('High', 'High'), ('Ave', 'Average'), ('Low', 'Low')], max_length=10)),
                ('severity', models.CharField(choices=[('Cri', 'Critical'), ('Ma', 'Major'), ('Mi', 'Minor'), ('Sug', 'Suggestion')], max_length=10)),
                ('frenquency', models.CharField(choices=[('Alw', 'Always'), ('Som', 'Sometimes'), ('Rand', 'Random'), ('NotTri', 'Not Tried'), ('NotRep', 'Not Reproducible'), ('Unknown', 'Unknown')], max_length=10)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stepsToReproduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('target_flow', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestEjecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('generalDescription', models.TextField()),
                ('implementationRelease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.implementationrelease')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('associatedRealease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status')),
                ('typeTask', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typetask')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.CharField(max_length=20)),
                ('record_id', models.IntegerField()),
                ('transDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePlatformAffected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.platform')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseCommercialApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('businessAreaAffected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.businessareaaffected')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status'),
        ),
        migrations.AddField(
            model_name='release',
            name='typeOfTests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests'),
        ),
        migrations.CreateModel(
            name='QaDocumentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TestPlans', models.TextField()),
                ('productOwnerApproval', models.BooleanField(default=False)),
                ('developerApproval', models.BooleanField(default=False)),
                ('importanceOfTestCases', models.TextField()),
                ('evidenceOfTheTestPlans', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeOfTests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests'),
        ),
        migrations.AddField(
            model_name='implementationrelease',
            name='Documentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qadocumentation'),
        ),
        migrations.AddField(
            model_name='implementationrelease',
            name='idRelease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release'),
        ),
        migrations.CreateModel(
            name='ChecklistDocumentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qaDocumentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qadocumentation')),
                ('releasePlatformAffected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.releaseplatformaffected')),
                ('typeOfTests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeoftests')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('caseTestDescription', models.TextField()),
                ('caseTestPreconditions', models.TextField()),
                ('caseOrderSteps', models.IntegerField()),
                ('caseSteps', models.TextField()),
                ('caseExpectedOutcome', models.TextField()),
                ('testEjecution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.testejecution')),
            ],
        ),
        migrations.AddField(
            model_name='businessareaaffected',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.release'),
        ),
    ]
