# Generated by Django 4.2.2 on 2023-08-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadocumentation',
            name='importanceOfTestCases',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MED', 'Media'), ('ALTA', 'Alta')], max_length=10),
        ),
    ]
