# Generated by Django 4.0.4 on 2023-07-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_businessunit_id_alter_typeoftests_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name_plural': 'Business Unit'},
        ),
        migrations.AlterModelOptions(
            name='typeoftests',
            options={'verbose_name_plural': 'Type of Tests'},
        ),
        migrations.RemoveField(
            model_name='businessareaaffected',
            name='release',
        ),
    ]
